name: Automerge de PR de develop a master.

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    branches: [ master ]

jobs:
  Crear-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.ref == 'develop'
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
    - name: Crear rama release
      run: |
        git checkout -B release-${{github.event.pull_request.head.title}}
        git push -u origin release-${{github.event.pull_request.head.title}}
  Pruebas-back:
    runs-on: ubuntu-latest
    if: " startsWith(github.event.head_commit.message, 'mezclar')"
    steps:
    - uses: actions/checkout@v2
      with:
        ref: release-${{github.event.pull_request.head.title}}
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m  pip install --upgrade pip
        if [ -f flaskr/requirements.txt ]; then pip install -r flaskr/requirements.txt; fi
    - name: Correr pruebas unitarias
      id: correr-test
      run: python -m unittest discover flaskr/tests -v
  Pruebas-front:
    runs-on: ubuntu-latest
    needs: Crear-release
    steps:
    - uses: actions/checkout@v2
      with:
        ref: release-${{github.event.pull_request.head.title}}
    - name: Set up Node.js 12.14
      uses: actions/setup-node@v1
      with:
        node-version: 12.14
    - name: Install dependencies
      run: |
        if [ -f front-end/tutorial-canciones/package.json ]; then npm --prefix front-end/tutorial-canciones/ install; fi
    - name: Correr pruebas unitarias
      id: correr-test
      run: ls

  Merge-to-main:  
    needs: [Pruebas-back, Pruebas-front]
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: release-${{github.event.pull_request.head.title}}
          target_branch: 'main'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'



    
  

